//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Settings.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class codedUIPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal codedUIPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Settings.Pages.codedUIPage", typeof(codedUIPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIWorkingPleasewaiPane {
		    get {
		        return ResourceManager.GetString("UIWorkingPleasewaiPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIWhereEdit {
		    get {
		        return ResourceManager.GetString("UIWhereEdit", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIRamadaColomboRoomsRaPane {
		    get {
		        return ResourceManager.GetString("UIRamadaColomboRoomsRaPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIContinueBooking2DoubHyperlink {
		    get {
		        return ResourceManager.GetString("UIContinueBooking2DoubHyperlink", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIFindCheapHotelsAccomWindow {
		    get {
		        return ResourceManager.GetString("UIFindCheapHotelsAccomWindow", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIItemPane {
		    get {
		        return ResourceManager.GetString("UIItemPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UILastnamesurnameEdit {
		    get {
		        return ResourceManager.GetString("UILastnamesurnameEdit", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIGreatnewsYougetFREEcPane {
		    get {
		        return ResourceManager.GetString("UIGreatnewsYougetFREEcPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIMRCustom {
		    get {
		        return ResourceManager.GetString("UIMRCustom", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIRamadaColomboHyperlink {
		    get {
		        return ResourceManager.GetString("UIRamadaColomboHyperlink", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIOrsigninusingHoorayCustom {
		    get {
		        return ResourceManager.GetString("UIOrsigninusingHoorayCustom", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIFeaturingcontemporarPane {
		    get {
		        return ResourceManager.GetString("UIFeaturingcontemporarPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UICheckinddmmyyEdit {
		    get {
		        return ResourceManager.GetString("UICheckinddmmyyEdit", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIFirstgivennamePane {
		    get {
		        return ResourceManager.GetString("UIFirstgivennamePane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIWwwhotelclubcomTraveDocument {
		    get {
		        return ResourceManager.GetString("UIWwwhotelclubcomTraveDocument", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIColomboHotelSearchReDocument {
		    get {
		        return ResourceManager.GetString("UIColomboHotelSearchReDocument", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIPhonenumberWeonlycalEdit {
		    get {
		        return ResourceManager.GetString("UIPhonenumberWeonlycalEdit", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIActualnightlyratesSaPane {
		    get {
		        return ResourceManager.GetString("UIActualnightlyratesSaPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIFindCheapHotelsAccomDocument {
		    get {
		        return ResourceManager.GetString("UIFindCheapHotelsAccomDocument", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIRamadaColomboCheckinPane {
		    get {
		        return ResourceManager.GetString("UIRamadaColomboCheckinPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIPreMainPane {
		    get {
		        return ResourceManager.GetString("UIPreMainPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIColomboDocument {
		    get {
		        return ResourceManager.GetString("UIColomboDocument", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UISigninoptionalSigninPane {
		    get {
		        return ResourceManager.GetString("UISigninoptionalSigninPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIMainPane {
		    get {
		        return ResourceManager.GetString("UIMainPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIDealslikethesegofastPane {
		    get {
		        return ResourceManager.GetString("UIDealslikethesegofastPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UISearchButton {
		    get {
		        return ResourceManager.GetString("UISearchButton", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIInterBodyPane {
		    get {
		        return ResourceManager.GetString("UIInterBodyPane", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIFromUS112RamadaColomDocument {
		    get {
		        return ResourceManager.GetString("UIFromUS112RamadaColomDocument", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIFirstgivennameEdit {
		    get {
		        return ResourceManager.GetString("UIFirstgivennameEdit", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIContinuebookingButton {
		    get {
		        return ResourceManager.GetString("UIContinuebookingButton", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UICheckoutddmmyyEdit {
		    get {
		        return ResourceManager.GetString("UICheckoutddmmyyEdit", resourceCulture);
		    }
		}
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string UIContinueButton {
		    get {
		        return ResourceManager.GetString("UIContinueButton", resourceCulture);
		    }
		}

    }
}