//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ProjectData : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProjectData defaultInstance = ((ProjectData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProjectData())));
        
        public static ProjectData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CURRENT_TEST_SUITE {
            get {
                return ((string)(this["CURRENT_TEST_SUITE"]));
            }
            set {
                this["CURRENT_TEST_SUITE"] = value;
            }
        }
    }
}
